defmodule TokengateWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :tokengate

  # The session is stored in an encrypted cookie (contents can be neither
  # read nor tampered with by the client). Salts and lifetime are
  # runtime-configurable via env vars. SESSION_COOKIE_SECURE=true forces the
  # Secure flag (HTTPS-only cookie); unset = Plug default (secure only when
  # the request itself is HTTPS, so HTTP deploys keep working).
  session_secure =
    case System.get_env("SESSION_COOKIE_SECURE") do
      v when v in ["true", "1"] -> [secure: true]
      v when v in ["false", "0"] -> [secure: false]
      _ -> []
    end

  @session_options [
                     store: :cookie,
                     key: "_tokengate_key",
                     signing_salt: System.get_env("SESSION_SIGNING_SALT", "TwS/TtVu"),
                     encryption_salt: System.get_env("SESSION_ENCRYPTION_SALT", "pScAXZ3eub"),
                     same_site: "Lax",
                     http_only: true,
                     # Sliding expiration: `renew: true` re-issues the cookie
                     # with a fresh max_age on every authenticated request, so
                     # an active user stays signed in while an idle browser
                     # expires after SESSION_MAX_AGE_SECONDS (default 4h).
                     renew: true,
                     max_age:
                       String.to_integer(System.get_env("SESSION_MAX_AGE_SECONDS", "14400"))
                   ] ++ session_secure

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :tokengate,
    gzip: not code_reloading?,
    only: TokengateWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :tokengate
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  plug TokengateWeb.Router
end
