import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :tokengate, TokengateWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# force_ssl is compile-time in Phoenix, so disabling it requires a BUILD-time
# switch: build the image with DISABLE_FORCE_SSL=1 (Dockerfile build ARG) for
# plain-HTTP deploys (e.g. VPN tunnel without a TLS terminator). At runtime,
# set PHX_SCHEME=http as well so generated URLs use http.
if System.get_env("DISABLE_FORCE_SSL") != "1" do
  config :tokengate, TokengateWeb.Endpoint,
    force_ssl: [
      rewrite_on: [:x_forwarded_proto],
      exclude: [hosts: ["localhost", "127.0.0.1"]]
    ]
end

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
